// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceUpdates {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<::substreams::pb::substreams::Clock>,
    #[prost(message, repeated, tag="2")]
    pub balance_updates: ::prost::alloc::vec::Vec<BalanceUpdate>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceUpdate {
    #[prost(string, tag="1")]
    pub contract: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub new_balance: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub transaction: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub call_path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfers {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<::substreams::pb::substreams::Clock>,
    #[prost(message, repeated, tag="2")]
    pub transfers: ::prost::alloc::vec::Vec<Transfer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(string, tag="1")]
    pub contract: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub memo: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub call_path: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
